USE [Inventory]
IF  NOT EXISTS (SELECT * FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'[dbo].[ADcomputer]') AND type in (N'U'))
	SET ANSI_NULLS ON
	SET QUOTED_IDENTIFIER ON
	CREATE TABLE [dbo].[ADcomputer](
		[AccountExpirationDate] [nvarchar](MAX) NULL,
		[accountExpires] [nvarchar](MAX) NULL,
		[AccountLockoutTime] [nvarchar](MAX) NULL,
		[AccountNotDelegated] [nvarchar](MAX) NOT NULL,
		[AllowReversiblePasswordEncryption] [nvarchar](MAX) NOT NULL,
		[BadLogonCount] [nvarchar](MAX) NULL,
		[CannotChangePassword] [nvarchar](MAX) NOT NULL,
		[CanonicalName] [nvarchar](MAX) NULL,
		[Certificates] [nvarchar](MAX) NULL,
		[CN] [nvarchar](MAX) NULL,
		[codePage] [nvarchar](MAX) NULL,
		[countryCode] [nvarchar](MAX) NULL,
		[Created] [nvarchar](MAX) NULL,
		[createTimeStamp] [nvarchar](MAX) NULL,
		[Deleted] [nvarchar](MAX) NULL,
		[Description] [nvarchar](MAX) NULL,
		[DisplayName] [nvarchar](MAX) NULL,
		[DistinguishedName] [nvarchar](MAX) NULL,
		[DNSHostName] [nvarchar](MAX) NULL,
		[DoesNotRequirePreAuth] [nvarchar](MAX) NOT NULL,
		[dSCorePropagationData] [nvarchar](MAX) NULL,
		[Enabled] [nvarchar](MAX) NOT NULL,
		[HomedirRequired] [nvarchar](MAX) NOT NULL,
		[HomePage] [nvarchar](MAX) NULL,
		[instanceType] [nvarchar](MAX) NULL,
		[IPv4Address] [nvarchar](MAX) NULL,
		[IPv6Address] [nvarchar](MAX) NULL,
		[isCriticalSystemObject] [nvarchar](MAX) NOT NULL,
		[isDeleted] [nvarchar](MAX) NULL,
		[LastBadPasswordAttempt] [nvarchar](MAX) NULL,
		[LastKnownParent] [nvarchar](MAX) NULL,
		[lastLogon] [nvarchar](MAX) NULL,
		[LastLogonDate] [nvarchar](MAX) NULL,
		[lastLogonTimestamp] [nvarchar](MAX) NULL,
		[localPolicyFlags] [nvarchar](MAX) NULL,
		[Location] [nvarchar](MAX) NULL,
		[LockedOut] [nvarchar](MAX) NOT NULL,
		[logonCount] [nvarchar](MAX) NULL,	
		[ManagedBy] [nvarchar](MAX) NULL,
		[MemberOf] [nvarchar](MAX) NULL,
		[MNSLogonAccount] [nvarchar](MAX) NOT NULL,
		[Modified] [nvarchar](MAX) NULL,
		[modifyTimeStamp] [nvarchar](MAX) NULL,
		[msDS-User-Account-Control-Computed] [nvarchar](MAX) NULL,
		[Name] [nvarchar](MAX) NULL,
		[nTSecurityDescriptor] [nvarchar](MAX) NULL,
		[ObjectCategory] [nvarchar](MAX) NULL,
		[ObjectClass] [nvarchar](MAX) NULL,
		[ObjectGUID] [nvarchar](MAX) NULL,
		[objectSid] [nvarchar](MAX) NULL,
		[OperatingSystem] [nvarchar](MAX) NULL,
		[OperatingSystemHotfix] [nvarchar](MAX) NULL,
		[OperatingSystemServicePack] [nvarchar](MAX) NULL,
		[OperatingSystemVersion] [nvarchar](MAX) NULL,
		[PasswordExpired] [nvarchar](MAX) NOT NULL,
		[PasswordLastSet] [nvarchar](255)NULL,
		[PasswordNeverExpires] [nvarchar](MAX) NOT NULL,
		[PasswordNotRequired] [nvarchar](MAX) NOT NULL,
		[PrimaryGroup] [nvarchar](MAX) NULL,
		[primaryGroupID] [nvarchar](MAX) NULL,
		[ProtectedFromAccidentalDeletion] [nvarchar](MAX) NOT NULL,
		[pwdLastSet] [nvarchar](MAX) NULL,
		[SamAccountName] [nvarchar](MAX) NULL,
		[sAMAccountType] [nvarchar](MAX) NULL,
		[sDRightsEffective] [nvarchar](MAX) NULL,
		[serverReferenceBL] [nvarchar](MAX) NULL,
		[ServiceAccount] [nvarchar](MAX) NULL,
		[servicePrincipalName] [nvarchar](MAX) NULL,
		[ServicePrincipalNames] [nvarchar](MAX) NULL,
		[SID] [nvarchar](MAX) NULL,
		[SIDHistory] [nvarchar](MAX) NULL,
		[TrustedForDelegation] [nvarchar](MAX) NOT NULL,
		[TrustedToAuthForDelegation] [nvarchar](MAX) NOT NULL,
		[UseDESKeyOnly] [nvarchar](MAX) NOT NULL,
		[userAccountControl] [nvarchar](MAX) NULL,
		[userCertificate] [nvarchar](MAX) NULL,
		[UserPrincipalName] [nvarchar](MAX) NULL,
		[uSNChanged] [nvarchar](MAX) NULL,
		[uSNCreated] [nvarchar](MAX) NULL,
		[whenChanged] [nvarchar](MAX) NULL,
		[whenCreated] [nvarchar](MAX) NULL
) ON [PRIMARY]
GO